# fly.toml app configuration file generated for fso-part11 on 2023-11-06T18:33:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fso-part11"
primary_region = "arn"

[build]
  [build.args]
    NODE_VERSION = "16.20.2"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
